Greeting="Hello I am a chatbot profile maker"
name=input("What is your name? ")
print("Hello " + name + " nice to meet you! ")
favourite_colour=input("What is your favourite color? ").lower()
age=int(input("How old are you? "))
Hobby=input("what is your Hobby? ")
Country=input("What country are you from? ")
print()
print()
print("\033[1;31m" + name + "profile\033[0m")
print("name:",name)
print("Age:",int(age))
print("Country:",Country)
print("Hobby:",Hobby)
print("favourite color:",favourite_colour)
